"use client";

import { Search, Sparkles, BookmarkCheck } from "lucide-react";

const features = [
  {
    icon: Search,
    title: "Smart Search",
    description:
      "Find the most relevant YouTube videos on any topic in seconds.",
  },
  {
    icon: Sparkles,
    title: "AI Summaries",
    description:
      "Get concise, accurate and structured summaries generated by AI.",
  },
  {
    icon: BookmarkCheck,
    title: "Save & Track",
    description:
      "Bookmark your summaries and track your learning progress.",
  },
];

export default function FeatureList() {
  return (
    <div className="mt-10 space-y-6">
      {features.map((feature) => {
        const Icon = feature.icon;

        return (
          <div key={feature.title} className="flex items-start gap-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white shadow">
              <Icon className="h-5 w-5 text-violet-600" />
            </div>

            <div>
              <h3 className="font-semibold text-gray-900">
                {feature.title}
              </h3>

              <p className="text-sm text-gray-600">
                {feature.description}
              </p>
            </div>
          </div>
        );
      })}
    </div>
  );
}